dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
os:
  - linux
  - osx
solution: Harmony.sln
mono:
  - latest
dotnet: 2.0.3
before_install:
  - if [ "$TRAVIS_COMMIT_MESSAGE" == "Update documentation" ]; then echo "Skipping documentation only commit" && exit; fi
install:
  - nuget restore
  - dotnet restore
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
  - msbuild /p:Configuration=Release
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe HarmonyTests/bin/Release/net45/HarmonyTests.dll
notifications:
  email: false
