version: 1.0.{build}

#########################################################################
### TODO: this fails because AppVeyor has no Visual Studio 2019 image yet
#########################################################################

max_jobs: 1
image: Visual Studio 2017
configuration: Release

before_build:
- nuget restore
- dotnet restore

artifacts:
- path: 'Harmony\bin\Release\Lib.Harmony.*.nupkg'
